### ISSUE TITLE
Level 2 Dialogue Box Text

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#92]
** Description **
The Dialogue text from the Dungeon Master at the start of level 2 is somewhat redundant. Appreciate the attempt but I don't think its necessary to keep around. I think it's best if we keep it to tutorial-esque text.

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/dfcf8e47-055c-4a8c-9836-f99d19624327)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/a5796fb9-698f-4b03-a3ce-55d258e5abe0)

** Version **
MainV4.03 / IssueTracking Branch

** OS **
Windows 10

**Comment by DefinitelyACat** [comment]
Text boxes have been removed as an overall component of the game. Now, however, with the text all being in the one place within the Level-Specific scrolls that come up at the start, having the extra lines of text help to fill out the scroll and give a little more filling for the instructions, rather than being a bland "You are here to destroy: click things to destroy".
